name: on_push

on:
  push:
    branch:
      - "**" # This will run on all branches, and must be quoted to be handled by yaml
  schedule:
    - cron: '*/10 * * * *' # This will run every 10th minute. Calculated with: https://crontab.guru/#*/10_*_*_*_*

jobs:

  build_and_test:
    runs-on: ubuntu-latest

    env:
      RUNNER_OS: true
      HEADLESS_CHROME: true

    steps:
      - name: Set start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
      - uses: kvrhdn/gha-buildevents@v1
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: tau-build-pipeline
          job-status: ${{ job.status }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 16
      - name: Run tests with maven
        working-directory: webdriver_java
        run: mvn test
      - name: Collect build data
        working-directory: webdriver_java
        env:
          PUSHGATEWAY_URL: ${{ secrets.PUSHGATEWAY_URL }}
        if: always()
        run: |
          echo "github_actions_total_duration $(expr $(date +%s) - ${START_TIME})" | curl --data-binary @- ${PUSHGATEWAY_URL}/metrics/job/github_actions
          ./resources/test_result_script.sh